name: AI Resume Analyzer CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  backend-build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Install backend dependencies
        run: npm install


      - name: Build backend
        run: npm run build



  frontend-build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Install frontend dependencies
        run: npm install


      - name: Build frontend
        run: npm run build